#spring:
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: localhost:9300
server:
  servlet:
    context-path: /ems
    
# 改由java config提供設定，High Level REST Client
#spring:
#  elasticsearch:
#    rest:
#      uris:
#      - http://localhost:9200